services:
  app:
    build: .
    container_name: express-app
    command: pnpm run dev
    ports:
      - "${DOCKER_PORT}:${BACKEND_PORT}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: